/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author ruinan
 */
public class location {
    
    private Random r;
   
    
    public location(int seed){
       this.r = new Random(seed); 
       
    }
    
    public Random getRandom(){
        return this.r;
    }
   
    /*
        An Arraylist to store the sequence of locations which randomly generated by Random with certain seed.
        The sequence eliminate the possibility of the location could be 'leave cities' at first generating.
    
    */
    public ArrayList<String> randomLocation(String[] locations,Random random){//test
        int index = 0;
        int count = locations.length;  
        ArrayList<String> loc = new ArrayList<>();//store locs;
        
        index = count-1;// To get rid of the leave city option at first generating
        int f = random.nextInt(index);
        loc.add(locations[f]);
        
        index = random.nextInt(count);// To generate locations randomly includes 'leave city' optionl
        loc.add(locations[index]);
        
        while(index != 4){// index depends on the leaving city element position
            index = random.nextInt(count);
            loc.add(locations[index]);
        }
        
        return loc; 
    }
   
   
}
