/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author ruinan
 */
public class location {
    
    private Random r;
   
    public location(){
    }
    
    public location(int seed){
       this.r = new Random(seed); 
       
    }
    
    public Random getRandom(){
        return this.r;
    }
   
    /*
        An Arraylist to store the sequence of locations which randomly generated by Random with certain seed.
        The sequence eliminate the possibility of the location could be 'leave cities' at first generating.
    
    */
    public ArrayList<String> randomLocation(String[] locations,location l){//test
        int index;
        int count;
        ArrayList<String> loc = new ArrayList<>();
        
        if(locations == null || locations.length == 0){
            return null;
        }
        else{
            count = locations.length;  
        }
        //store locs;
        
        if(count >0){
            
            String first = l.randomGenerating(count-1,l.getRandom(),locations);
            loc.add(first);
            //System.out.println(first);
            String sub = l.randomGenerating(count,l.getRandom(),locations);
            //System.out.println(sub);
            while(!sub.equals("leave")){
                loc.add(sub);
                sub = l.randomGenerating(count,l.getRandom(),locations);
                System.out.println(sub);
            }
           
        }
        return loc;
       
    }
    
    public String randomGenerating(Integer range, Random r, String[] s){
        
        return s[r.nextInt(range)];
        
    }
   
   
}
